use_frameworks!

platform :ios, '13.0'

target 'ZHHMediaScrollView_Example' do
  pod 'ZHHMediaScrollView', :path => '../'

  target 'ZHHMediaScrollView_Tests' do
    inherit! :search_paths
    
  end
end
